name: D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    strategy:
        matrix:
          os: [ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
    
    - if: contains(matrix.os, 'windows')
      name: Install SDL2 (Windows)
      shell: bash
      run: |
        curl https://github.com/libsdl-org/SDL/releases/download/release-2.26.4/SDL2-2.26.4-win32-x64.zip --output sdl2.zip
        unzip sdl2.zip
        mv SDL2.dll sdl2.dll
        curl https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12-win32-x64.zip --output sdl2_ttf.zip
        unzip sdl2_ttf.zip
        mv SDL2_ttf.dll sdl2_ttf.dll
        
    - if: contains(matrix.os, 'ubuntu'
      name: Install SDL2 (Ubuntu)
      shell: bash
      run: |
        sudo apt install libsdl2-dev libsdl2-2.0-0 -y
        sudo apt install libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0-0 -y;
  
    - name: "Build"
      run: |
        dub build --compiler=dmd
