# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
    
    - name: Download SDL2
      # You may pin to the exact commit or the version.
      # uses: albin-johansson/download-sdl2@d4e9339339b31b200ada5c7530d5eadad01576c2
      uses: albin-johansson/download-sdl2@v2
      with:
        # Where the SDL2 sources will be saved
        sources_destination: .
        # Where the SDL2 runtime binaries will be saved
        binaries_destination: .
        
    - name: Download SDL2_ttf
      # You may pin to the exact commit or the version.
      # uses: albin-johansson/download-sdl2-ttf@620593c424dbe412921ea1b4f2c6ccde77818516
      uses: albin-johansson/download-sdl2-ttf@v1
      with:
        # Where the SDL2_ttf sources will be saved
        sources_destination: .
        # Where the SDL2_ttf runtime binaries will be saved
        binaries_destination: .

    - name: 'Build & Test'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler=$DC
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test --compiler=$DC
